import { DataProps } from "../topic-filters/select-input";
// prettier-ignore
export const topicFilterOptions: DataProps[] = [
    { key: "topic_0", label: "Volkswirtschaft", searchList: ['steuerreform', 'finanzpolit', 'aufschwung', 'steuererhoh', 'haushaltsplan', 'arbeitsmarktpolit', 'arbeitslosengeld', 'haushaltsjahr', 'mehrwertsteu', 'steuersenk', 'haushaltspolit', 'steuereinnahm', 'langzeitarbeitslos', 'steuersatz', 'einkommensteu', 'neuverschuld', 'umsatzsteu', 'inflation', 'haushaltsentwurf', 'vermogensteu', 'steuerrecht', 'nachtragshaushalt', 'arbeitsamt', 'bruttosozialprodukt', 'zonenrandgebiet', 'jahreswirtschaftsbericht', 'strukturpolit', 'rechnungsjahr', 'gemeinschaftsaufgab', 'volkerrecht'] },
    { key: "topic_1", label: "Bürger:Innenrechte", searchList: ['menschenrecht', 'fluchtling', 'polizei', 'arzt', 'behinder', 'petition', 'datenschutz', 'staatsangehor', 'demonstration', 'petitionsausschuss', 'weiterbild', 'diktatur', 'behind', 'asylbewerb', 'zuwander', 'gerichtshof', 'menschenrechtsverletz', 'sozialismus', 'gewalttat', 'aussiedl', 'kommunist', 'jud', 'rechtsextremismus', 'polizist', 'asyl', 'asylrecht', 'todesstraf', 'eingab', 'migration', 'religion'] },
    { key: "topic_2", label: "Gesundheitswesen", searchList: ['krankenversicher', 'patient', 'krankenhaus', 'krankenkass', 'arzt', 'gesundheitswes', 'versich', 'gesundheitspolit', 'arzneimittel', 'medikament', 'apothek', 'spend', 'gesundheitsreform', 'heim', 'patientinn', 'gesundheitssyst', 'zuzahl', 'arzneimitteln', 'roma', 'beitragssatz', 'selbststand', 'selbstverwalt', 'bundesgesundheitsamt', 'interpellation', 'organsp', 'pandemi', 'selbstbeteil', 'klinik', 'pharmaindustri', 'kulturgut'] },
    { key: "topic_3", label: "Landwirtschaft", searchList: ['landwirt', 'agrarpolit', 'tier', 'wald', 'lebensmittel', 'milch', 'tierschutz', 'hektar', 'getreid', 'lebensmitteln', 'kennzeichn', 'rechnungshof', 'ha', 'agrarbericht', 'bauernverband', 'forstwirtschaft', 'wirtschaftsjahr', 'einfahr', 'tierhalt', 'hof', 'familienbetrieb', 'agrarstruktur', 'marktordn', 'tierversuch', 'kuh', 'zuck', 'altershilf', 'nahrungsmittel', 'landwirtschaftsminist', 'ernahrungsausschuss'] },
    { key: "topic_4", label: "Arbeit", searchList: ['mindestlohn', 'mitbestimm', 'arbeitnehmerinn', 'betriebsrat', 'tarifvertrag', 'arbeitszeit', 'tarifpartn', 'ig', 'schwarzarbeit', 'beschaftigungsverhaltnis', 'kinderbetreu', 'kundigungsschutz', 'tarifautonomi', 'metall', 'leiharbeit', 'kurzarbeit', 'betriebsverfassungsgesetz', 'betreuungsgeld', 'gewerkschaftsbund', 'uberstund', 'fusion', 'belegschaft', 'arbeitszeitverkurz', 'lohnfortzahl', 'streik', 'sozialversicherungsbeitrag', 'mitbestimmungsrecht', 'zeitarbeit', 'arbeitsvertrag', 'tarifvertragspartei'] },
    { key: "topic_5", label: "Bildung", searchList: ['hochschul', 'bafog', 'ausbildungsplatz', 'studier', 'film', 'bildungspolit', 'studium', 'berufsausbild', 'kunstl', 'auszubild', 'forschungsforder', 'berufsbild', 'bildungswes', 'forschungseinricht', 'jugendarbeitslos', 'wissenschaftsrat', 'grundlagenforsch', 'ausbildungsforder', 'forschungspolit', 'forsch', 'kultusminist', 'studienplatz', 'bildungssyst', 'schulerinn', 'lehrstell', 'fachhochschul', 'studiengebuhr', 'hochschulpakt', 'lehrling', 'abitur'] },
    { key: "topic_6", label: "Umwelt", searchList: ['klimaschutz', 'umweltpolit', 'fahrzeug', 'stoff', 'emission', 'abfall', 'kernkraftwerk', 'klimawandel', 'grenzwert', 'automobilindustri', 'entsorg', 'co', 'emissionshandel', 'umweltminist', 'energieeffizienz', 'larm', 'naturschutz', 'meer', 'fluss', 'gewass', 'endlag', 'schadstoff', 'umlag', 'trinkwass', 'bundesumweltminist', 'klimapolit', 'mull', 'umweltausschuss', 'endlager', 'altlast'] },
    { key: "topic_7", label: "Energie", searchList: ['kernenergi', 'naturschutz', 'reaktorsich', 'energiepolit', 'strom', 'energieversorg', 'energiew', 'technikfolgenabschatz', 'aussteig', 'bergbau', 'kraftwerk', 'atomkraftwerk', 'atomenergi', 'stadtentwickl', 'steinkohl', 'ol', 'gas', 'genehmigungsverfahr', 'energietrag', 'kernkraftwerk', 'lit', 'verbraucherschutz', 'benzin', 'strompreis', 'reaktor', 'energieeinspar', 'energiewirtschaft', 'tourismus', 'atomkraft', 'bergleut'] },
    { key: "topic_8", label: "Transport", searchList: ['bahn', 'bundesbahn', 'schien', 'schiff', 'verkehrspolit', 'autobahn', 'auto', 'km', 'strassenbau', 'eisenbahn', 'strassenverkehr', 'verkehrstrag', 'maut', 'lkw', 'verkehrsminist', 'autos', 'verkehrsausschuss', 'haf', 'pkw', 'bundesverkehrsminist', 'kust', 'bundesstrass', 'see', 'guterverkehr', 'bundesverkehrswegeplan', 'autofahr', 'verkehrsinfrastruktur', 'luftverkehr', 'nahverkehr', 'personennahverkehr'] },
    { key: "topic_9", label: "Recht & Kriminalität", searchList: ['mutt', 'richt', 'straftat', 'vat', 'verbrech', 'terrorismus', 'straf', 'ehe', 'strafrecht', 'mord', 'kriminalitat', 'senat', 'madch', 'anschlag', 'staatsanwaltschaft', 'terrorist', 'strafgesetzbuch', 'terror', 'familienpolit', 'ehegatt', 'bundesgerichtshof', 'rechtspolit', 'gefang', 'rechtsanwalt', 'stgb', 'gefangnis', 'drog', 'steuerhinterzieh', 'bundeskriminalamt', 'freiheitsstraf'] },
    { key: "topic_10", label: "Sozialpolitik", searchList: ['rent', 'rentenversicher', 'rentn', 'pfleg', 'armut', 'angestellt', 'kindergeld', 'sozialhilf', 'pflegeversicher', 'unfall', 'kriegsopf', 'beitragszahl', 'unfallversicher', 'rentenreform', 'altersvorsorg', 'riest', 'rentnerinn', 'massenarbeitslos', 'existenzminimum', 'kriegsopferversorg', 'alleinerzieh', 'bundeszuschuss', 'beitragssatz', 'witw', 'arbeitslosenhilf', 'pflegebedurft', 'einkommensgrenz', 'rucklag', 'jugendhilf', 'regelsatz'] },
    { key: "topic_11", label: "Wohnungswesen", searchList: ['wohnung', 'miet', 'wohnungsbau', 'grundstuck', 'wohngeld', 'selbstverwalt', 'raumordn', 'stadtebau', 'vermiet', 'wohnraum', 'wohnungswes', 'bauwirtschaft', 'wohnungsmarkt', 'bauwes', 'wohnungsbaus', 'mietrecht', 'wohnungspolit', 'kommunalpolit', 'enteign', 'ratsprasidentschaft', 'stadtebauforder', 'sozialwohn', 'verausser', 'wohnungswirtschaft', 'mieterhoh', 'bauarbeit', 'eigenheim', 'mieterinn', 'wohnungsnot', 'eigenheimzulag'] },
    { key: "topic_12", label: "Binnenhandel", searchList: ['bank', 'mittelstand', 'verbraucherschutz', 'aufsichtsrat', 'verbraucherinn', 'finanzmarkt', 'kapitalmarkt', 'gmbh', 'akti', 'existenzgrund', 'sparkass', 'einzelhandel', 'aktionar', 'aktiengesellschaft', 'glaubig', 'urheberrecht', 'insolvenz', 'anleg', 'mittelstandl', 'kreditinstitut', 'patent', 'eigenkapital', 'autor', 'urheb', 'anti', 'beratungsstell', 'bors', 'verlag', 'rechtsform', 'manag'] },
    { key: "topic_13", label: "Verteidigungspolitik", searchList: ['bundeswehr', 'soldat', 'waff', 'streitkraft', 'mandat', 'wehrpflicht', 'abrust', 'trupp', 'soldatinn', 'sicherheitspolit', 'verteidigungsminist', 'verteidigungsausschuss', 'wehrbeauftragt', 'export', 'arme', 'mission', 'pakt', 'atomwaff', 'militar', 'general', 'offizi', 'liefer', 'auss', 'verteidigungsministerium', 'zivildien', 'raket', 'rustung', 'wehrdien', 'auslandseinsatz', 'rustungsexport'] },
    { key: "topic_14", label: "Technologie", searchList: ['fernseh', 'digitalisier', 'rundfunk', 'anstalt', 'ratifizier', 'sendung', 'raumfahrt', 'rundfunkanstalt', 'grossprojekt', 'liegenschaft', 'transformation', 'it', 'breitbandausbau', 'satellit', 'japan', 'frequenz', 'radio', 'tierarzt', 'bildschirm', 'raumfahrtindustri', 'send', 'weltraum', 'groko', 'fernsehprogramm', 'ratifikation', 'ausstrahl', 'versteiger', 'digitalpakt', 'fernsehanstalt', 'intellektuell'] },
    { key: "topic_15", label: "Außenhandel", searchList: ['zins', 'globalisier', 'weltwirtschaft', 'welthandel', 'export', 'inflationsrat', 'protektionismus', 'freihandelsabkomm', 'handelspolit', 'ttip', 'zin', 'handelsabkomm', 'leistungsbilanz', 'wechselkurs', 'freihandel', 'schwerpunktsetz', 'wirtschaftsbezieh', 'handelspartn', 'weltwirtschaftsgipfel', 'expo', 'wirtschaftssyst', 'okonom', 'abschott', 'haushaltsdefizit', 'leistungsbilanzdefizit', 'direktinvestition', 'zinsniveau', 'zollunion', 'kapitalmarkt', 'zinssatz'] },
    { key: "topic_16", label: "Außenpolitik", searchList: ['entwicklungsland', 'entwicklungspolit', 'entwicklungshilf', 'entwicklungszusammenarbeit', 'wahrungsunion', 'sicherheitsrat', 'hung', 'europapolit', 'soldat', 'burgerkrieg', 'partnerland', 'zivilbevolker', 'nichtregierungsorganisation', 'staatengemeinschaft', 'nationalstaat', 'friedensprozess', 'sudsudan', 'vertief', 'brit', 'taliban', 'regierungskonferenz', 'kinderarbeit', 'us', 'zivilist', 'eskalation', 'schwellenland', 'trupp', 'sicherheitskraft', 'waffenstillstand', 'einigungsprozess'] },
    { key: "topic_17", label: "Öffentliche Verwaltung", searchList: ['gemeind', 'beamt', 'ag', 'okosteu', 'wahlrecht', 'bundespost', 'fernmeldewes', 'lohnnebenkost', 'gewerbesteu', 'foderalismus', 'korruption', 'finanzausgleich', 'verwaltungsrat', 'ruhrgebiet', 'versohn', 'verfassungsrecht', 'planstell', 'volksentscheid', 'zulag', 'referat', 'volksrepubl', 'finanzreform', 'volkskamm', 'ruhestand', 'volksabstimm', 'interessenvertret', 'beamtenrecht', 'affar', 'pension', 'finanzausstatt'] },
    { key: "topic_18", label: "Sport", searchList: ['sport', 'sportl', 'sportverein', 'stammzell', 'sportausschuss', 'fussball', 'spitzensport', 'sportbund', 'embryon', 'sportforder', 'sportstatt', 'mannschaft', 'breitensport', 'fussballweltmeisterschaft', 'klon', 'athlet', 'zell', 'sportpolit', 'sportverband', 'leistungssport', 'sportlerinn', 'sportanlag', 'stammzellforsch', 'train', 'sportbericht', 'sportart', 'sportorganisation', 'embryonenschutzgesetz', 'spitzensportl', 'embryo'] },
    { key: "topic_19", label: "Wiedervereinigung", searchList: ['entspann', 'treuhandanstalt', 'entspannungspolit', 'einigungsvertrag', 'ostpolit', 'auswart', 'ostdeutsch', 'schlussakt', 'friedenspolit', 'zusammenwachs', 'grundvertrag', 'isolier', 'viermachteabkomm', 'ostvertrag', 'formeln', 'weltmacht', 'korb', 'ostblockstaat', 'beitrittsgebiet', 'westdeutsch', 'regierungsbild', 'investitionshemmnis', 'friedenssicher', 'einmarsch', 'weizsack', 'rahmenbeschluss', 'koexistenz', 'teilnehmerstaat', 'mauerfall', 'fachaufsicht'] },
    { key: "topic_20", label: "Volkswirtschaft: Steuern", searchList: ['steuerreform', 'mehrwertsteu', 'steuersenk', 'steuersatz', 'einkommensteu', 'umsatzsteu', 'vermogensteu', 'steuerrecht', 'finanzamt', 'korperschaftsteu', 'steuerpflicht', 'spitzensteuersatz', 'erbschaftsteu', 'mehrwertsteuererhoh', 'freibetrag', 'steuerentlast', 'bemessungsgrundlag', 'finanzverwalt', 'steuerausfall', 'steuersyst', 'lohnsteu', 'steuerbelast', 'progression', 'steuererhoh', 'unternehmensteuerreform', 'steuervergunst', 'gewerbekapitalsteu', 'steuergesetz', 'kapitalgesellschaft', 'gewerbesteu'] },
    { key: "topic_21", label: "Volkswirtschaft: Haushalt", searchList: ['finanzpolit', 'haushaltsplan', 'haushaltsjahr', 'steuererhoh', 'haushaltspolit', 'neuverschuld', 'haushaltsentwurf', 'steuereinnahm', 'nachtragshaushalt', 'rechnungsjahr', 'nettokreditaufnahm', 'haushaltsgesetz', 'mehrausgab', 'minderausgab', 'steuerschatz', 'haushaltsansatz', 'staatsfinanz', 'staatsverschuld', 'billion', 'stabilitatspakt', 'kreditaufnahm', 'ausgabenseit', 'altschuld', 'anleih', 'sparpaket', 'haushaltsrecht', 'steuermehreinnahm', 'haushaltsfuhr', 'wachstumspakt', 'soliditat'] },
    { key: "topic_22", label: "Bürger:Innenrechte: Gleichstellung", searchList: ['todesstraf', 'elterngeld', 'teilzeit', 'teilzeitarbeit', 'lebenspartnerschaft', 'fuhrungsposition', 'schwul', 'frauenforder', 'lesb', 'frauenquot', 'frauenanteil', 'teilzeitbeschaft', 'lebenspartn', 'gleichstellungspolit', 'elternzeit', 'vollzeit', 'todesurteil', 'vollstreck', 'schlusseltechnologi', 'quotier', 'arbeitszeit', 'frauentag', 'auskunftsanspruch', 'spitzenposition', 'wiedereinstieg', 'gleichstellungsgesetz', 'hinricht', 'frauenrecht', 'rechtsinstitut', 'entgeltgleich'] },
    { key: "topic_23", label: "Bürger:Innenrechte: Datenschutz", searchList: ['datenschutz', 'gerichtshof', 'burgerinitiativ', 'brud', 'vorratsdatenspeicher', 'datenschutzbeauftragt', 'personalausweis', 'datei', 'schwest', 'speicher', 'bundesbeauftragt', 'privatsphar', 'personlichkeitsrecht', 'bundesdatenschutzgesetz', 'informationstechn', 'tatigkeitsbericht', 'datenverarbeit', 'sicherheitsbehord', 'report', 'datenbank', 'ubermittl', 'datenschutzrecht', 'datenaustausch', 'vertragsverletzungsverfahr', 'identifizier', 'hilfskraft', 'abruf', 'bundesdatenschutzbeauftragt', 'datenschutzgesetz', 'volkszahlungsurteil'] },
    { key: "topic_24", label: "Bürger:Innenrechte: Flucht, Asyl & Einbürgerung", searchList: ['fluchtling', 'staatsangehor', 'weiterbild', 'asylbewerb', 'zuwander', 'aussiedl', 'asyl', 'asylrecht', 'migration', 'migrant', 'abschieb', 'pass', 'asylverfahr', 'ruckfuhr', 'einreis', 'zuwand', 'herkunftsland', 'kontingent', 'einwander', 'fluchtursach', 'asylantrag', 'aufenthaltsrecht', 'asylbewerberleistungsgesetz', 'ubersiedl', 'migrantinn', 'familiennachzug', 'asylsuch', 'auslandergesetz', 'migrationshintergrund', 'integrationspolit'] },
    { key: "topic_25", label: "Gesundheitswesen: Covid19", searchList: ['pandemi', 'kulturgut', 'zuruckweis', 'coronakris', 'virus', 'coronapandemi', 'impfstoff', 'juristenausbild', 'poststell', 'kulturerb', 'lockdown', 'welterbestatt', 'hirn', 'personalaufwand', 'schaustell', 'samml', 'stimmausweis', 'spitzenpolit', 'postversorg', 'masslos', 'weltkulturerb', 'schieflieg', 'coronazeit', 'schutzausrust', 'horensag', 'videokonferenz', 'quarantan', 'akzentverschieb', 'bundestagsgrupp', 'postschalt'] },
    { key: "topic_26", label: "Landwirtschaft: Nahrungsmittel", searchList: ['lebensmittel', 'lebensmitteln', 'kennzeichn', 'nahrungsmittel', 'untersuchungsergebnis', 'kennzeichnungspflicht', 'lebensmittelrecht', 'labor', 'futtermittel', 'futtermitteln', 'fett', 'lebensmittelgesetz', 'liquidation', 'volksgesund', 'zuck', 'inhaltsstoff', 'reichsbank', 'lebensmitteluberwach', 'erzeugnis', 'verpack', 'zusatzstoff', 'patentschutz', 'anbauverbot', 'efsa', 'gesundheitsbehord', 'fondslos', 'ernahrungsministerium', 'lebensmittelwirtschaft', 'bestrahl', 'salz'] },
    { key: "topic_27", label: "Landwirtschaft: Tierschutz", searchList: ['tier', 'tierschutz', 'tierversuch', 'tierhalt', 'tierschutzgesetz', 'antibiotika', 'stall', 'parlamentsreform', 'massentierhalt', 'nutztierhalt', 'nutzti', 'tiertransport', 'tierwohl', 'wohlbefind', 'unterhaus', 'sau', 'tierseuch', 'tierschutzbericht', 'kaninch', 'versuchsti', 'bmel', 'mitgeschopf', 'haltungsbeding', 'tierart', 'wildti', 'tiergesund', 'antibiotikaeinsatz', 'schwein', 'schlachthof', 'tierqualerei'] },
    { key: "topic_28", label: "Arbeit: Arbeitnehmer:Innenrechte", searchList: ['mitbestimm', 'betriebsrat', 'tarifvertrag', 'tarifpartn', 'ig', 'kundigungsschutz', 'metall', 'betriebsverfassungsgesetz', 'tarifautonomi', 'gewerkschaftsbund', 'belegschaft', 'lohnfortzahl', 'streik', 'mitbestimmungsrecht', 'sozialpartn', 'tarifvertragspartei', 'arbeitgeberverband', 'krankheitsfall', 'montan', 'arbeitnehmerschaft', 'tarifpartei', 'tarifverhandl', 'arbeitskampf', 'konkur', 'sozialplan', 'sozialausschuss', 'kundigungsfrist', 'kapitalismus', 'tarifpolit', 'arbeiterschaft'] },
    { key: "topic_29", label: "Arbeit: Mindestlohn", searchList: ['mindestlohn', 'arbeitnehmerinn', 'beschaftigungsverhaltnis', 'arbeitsbeschaffungsmassnahm', 'entsendegesetz', 'minijob', 'niedriglohnsektor', 'tarifvertrag', 'tarifbind', 'tarifautonomi', 'tariflohn', 'stundenlohn', 'lohndumping', 'niedriglohn', 'niedriglohnbereich', 'lohnuntergrenz', 'arbeitsmarktreform', 'dumpinglohn', 'lohnniveau', 'lohnfind', 'hungerlohn', 'arbeitsministerin', 'kombilohn', 'mindestlohnkommission', 'allgemeinverbind', 'allgemeinverbindlichkeitserklar', 'vollzeit', 'geringqualifiziert', 'untergrenz', 'vollzeitarbeitsplatz'] },
    { key: "topic_30", label: "Arbeit: Leih- & Zeitarbeit", searchList: ['leiharbeit', 'zeitarbeit', 'arbeitsvertrag', 'munition', 'verleih', 'informationspolit', 'arbeitnehmeruberlass', 'korrespondenz', 'arbeitnehmeruberlassungsgesetz', 'leiharbeitnehm', 'lohndumping', 'vorgesprach', 'implikation', 'stammbelegschaft', 'schleck', 'zeitnot', 'zeitarbeitnehm', 'tarifvertrag', 'entleih', 'gleichbehandlungsgrundsatz', 'normalburg', 'auftragsspitz', 'zeitarbeitsunternehm', 'zeitarbeitsbranch', 'umsatzsteuerbefrei', 'wahlversamml', 'zeitarbeitsfirm', 'gesamtwerk', 'tarifgemeinschaft', 'versorgungsbetrieb'] },
    { key: "topic_31", label: "Bildung: Hochschule & Unversität", searchList: ['hochschul', 'bafog', 'studier', 'studium', 'wissenschaftsrat', 'ausbildungsforder', 'studienplatz', 'fachhochschul', 'studiengebuhr', 'hochschulpakt', 'hochschulrahmengesetz', 'studiengang', 'bundesausbildungsforderungsgesetz', 'nachwuchs', 'hochschulbau', 'freibetrag', 'wissenschaftlerinn', 'bedarfssatz', 'hochschullehr', 'exzellenzinitiativ', 'forschungseinricht', 'student', 'hochschulbereich', 'pakt', 'fakultat', 'hochschulpolit', 'studentinn', 'studienreform', 'absolvent', 'studienanfang'] },
    { key: "topic_32", label: "Bildung: Schule", searchList: ['bildungspolit', 'bildungswes', 'kultusminist', 'bildungssyst', 'schulerinn', 'abitur', 'bildungsbereich', 'ganztagsschul', 'kultusministerkonferenz', 'gesamtschul', 'bildungsplan', 'kooperationsverbot', 'abiturient', 'bildungschanc', 'bildungseinricht', 'bildungsbericht', 'bildungssystem', 'lehrerinn', 'grundschul', 'schulwes', 'bildungsgesamtplan', 'begab', 'gymnasium', 'schuljahr', 'verwaltungsabkomm', 'hauptschul', 'bildungsgipfel', 'durchlass', 'schulsyst', 'padagog'] },
    { key: "topic_33", label: "Bildung: Berufliche Ausbildung", searchList: ['ausbildungsplatz', 'berufsausbild', 'auszubild', 'berufsbild', 'jugendarbeitslos', 'lehrstell', 'lehrling', 'berufsbildungsbericht', 'ausbildungsstatt', 'berufsbildungsgesetz', 'berufsschul', 'jugendarbeitsschutzgesetz', 'ausbildungsberuf', 'ausbildungsstell', 'ausbildungsordn', 'warteschleif', 'ausbildungspakt', 'ausbildungsvertrag', 'ausbildungsmarkt', 'ausbildungssyst', 'jump', 'ausbildungsvergut', 'ausbildungsplatzabgab', 'bundesinstitut', 'ausbildungsplatzangebot', 'ausbildungsbetrieb', 'ausbildungsgang', 'schulabgang', 'berufserfahr', 'berufswahl'] },
    { key: "topic_34", label: "Bildung: Forschung", searchList: ['forschungsforder', 'grundlagenforsch', 'forschungspolit', 'forsch', 'forschungseinricht', 'forschungsergebnis', 'technologiepolit', 'biotechnologi', 'forschungsvorhab', 'forschungsprogramm', 'forschungsprojekt', 'bmbf', 'hightech', 'forschungsminist', 'forschungsgemeinschaft', 'forschungsbereich', 'forschungslandschaft', 'mikroelektron', 'projektforder', 'forschungsministerium', 'energieforsch', 'innovationskraft', 'gesundheitsforsch', 'innovationsfah', 'forschungsmittel', 'innovationspolit', 'forschungshaushalt', 'rahmenprogramm', 'forschungsarbeit', 'bmft'] },
    { key: "topic_35", label: "Umwelt: Atommüll & Chemische Giftstoffe", searchList: ['umweltpolit', 'stoff', 'kernkraftwerk', 'entsorg', 'endlag', 'abfall', 'endlager', 'chemikali', 'sicherheitsstandard', 'atommull', 'umweltbundesamt', 'brennelement', 'zwischenlag', 'umweltfrag', 'wiederaufarbeit', 'gorleb', 'umweltminist', 'sachzusammenhang', 'umweltbereich', 'umweltschad', 'lager', 'schacht', 'umweltproblem', 'erkund', 'castor', 'atomgesetz', 'vergift', 'salzstock', 'gesundheitsschutz', 'bundesumweltminist'] },
    { key: "topic_36", label: "Umwelt: Dieselskandal", searchList: ['fahrzeug', 'automobilindustri', 'fahrverbot', 'diesel', 'grenzwert', 'autoindustri', 'nachrust', 'autos', 'messung', 'pkw', 'mikrogramm', 'automobilherstell', 'krisch', 'dieselfahrzeug', 'verkehrsminist', 'umwelthilf', 'kraftfahrt', 'klamauk', 'plakett', 'zulieferindustri', 'pkws', 'scheffel', 'messstell', 'dieselmotor', 'schlusselindustri', 'niederschrift', 'hardwarenachrust', 'abgaswert', 'messwert', 'autoherstell'] },
    { key: "topic_37", label: "Umwelt: Klima- & Umweltschutz", searchList: ['klimaschutz', 'naturschutz', 'reaktorsich', 'technikfolgenabschatz', 'emission', 'klimawandel', 'stadtentwickl', 'emissionshandel', 'grenzwert', 'co', 'energieeffizienz', 'verbraucherschutz', 'meer', 'fluss', 'gewass', 'umlag', 'tourismus', 'trinkwass', 'klimapolit', 'go', 'schadstoff', 'klimaschutzziel', 'umweltministerium', 'umweltausschuss', 'gebaudesanier', 'grundwass', 'zertifikat', 'abwass', 'umweltminist', 'fischerei'] },
    { key: "topic_38", label: "Energie: Kernenergie", searchList: ['kernenergi', 'naturschutz', 'reaktorsich', 'technikfolgenabschatz', 'aussteig', 'kraftwerk', 'energieversorg', 'atomkraftwerk', 'atomenergi', 'stadtentwickl', 'genehmigungsverfahr', 'kernkraftwerk', 'verbraucherschutz', 'reaktor', 'energieeinspar', 'tourismus', 'atomkraft', 'go', 'brut', 'energiequell', 'atomgesetz', 'atomausstieg', 'kohlekraftwerk', 'energieverbrauch', 'energietrag', 'kernkraft', 'plutonium', 'uran', 'inbetriebnahm', 'zusatzpunktlist'] },
    { key: "topic_39", label: "Energie: Fossile Energie", searchList: ['ol', 'gas', 'lit', 'benzin', 'erdgas', 'tankstell', 'erdol', 'bergrecht', 'pipelin', 'fracking', 'benzinpreis', 'gesetzesbeschluss', 'spielzeug', 'elektrizitat', 'dieselkraftstoff', 'verhandlungsrund', 'kraftstoff', 'anrufungsbegehr', 'mineralolwirtschaft', 'asb', 'endverbrauch', 'diesel', 'kubikmet', 'vorkomm', 'anreizregulier', 'sprit', 'lagerstatt', 'mineralolkonzern', 'heruntergegang', 'kabinettsausschuss'] },
    { key: "topic_40", label: "Energie: Erneuerbare Energie", searchList: ['elektromobilitat', 'wasserstoff', 'kraftstoff', 'duldung', 'bonus', 'zukunftsprogramm', 'batteri', 'bleiberechtsregel', 'elektrofahrzeug', 'antrieb', 'elektroautos', 'fraktionsfuhr', 'lot', 'aufenthaltserlaubnis', 'verbrennungsmotor', 'aufenthaltsgesetz', 'bleiberecht', 'modellregion', 'mag', 'haushaltssanier', 'herbstgutacht', 'ausrustungsinvestition', 'lichkeit', 'technologieoff', 'brei', 'herkulesaufgab', 'kettenduld', 'unterbewert', 'darm', 'weltmarktfuhr'] },
    { key: "topic_41", label: "Transport: Automobil & Straßenverkehr", searchList: ['autobahn', 'auto', 'km', 'strassenbau', 'strassenverkehr', 'maut', 'lkw', 'autos', 'pkw', 'bundesstrass', 'autofahr', 'personennahverkehr', 'verkehrssich', 'verkehrsinfrastruktur', 'opnv', 'bundesfernstrass', 'wag', 'zweckbind', 'verkehrspolit', 'bundesautobahn', 'bundesverkehrsministerium', 'verkehrsteilnehm', 'verkehrsmittel', 'fahrrad', 'unfall', 'bedarfsplan', 'siedlung', 'bus', 'strassennetz', 'kraftfahr'] },
    { key: "topic_42", label: "Transport: Flug", searchList: ['luftverkehr', 'flugsicher', 'flug', 'flughaf', 'flugverkehr', 'luftraum', 'passagi', 'fluggesellschaft', 'einfuhrungsgesetz', 'bundesschatzminist', 'luftfahrt', 'kommissionsbericht', 'luftverkehrsgesetz', 'fluglots', 'selbsttot', 'abschlagszahl', 'singl', 'pflichtverletz', 'flugbeweg', 'luftfahrzeug', 'flugplatz', 'flugsich', 'einsam', 'zolltarifgesetz', 'pilot', 'eurocontrol', 'kerosin', 'verkehrsausschuss', 'luftsich', 'bundesverkehrsminist'] },
    { key: "topic_43", label: "Transport: Bahn", searchList: ['bahn', 'bundesbahn', 'schien', 'verkehrspolit', 'eisenbahn', 'verkehrstrag', 'bundesverkehrswegeplan', 'verkehrsminist', 'guterverkehr', 'verkehrsausschuss', 'bundesverkehrsminist', 'bahnhof', 'binnenschiffahrt', 'bahnreform', 'schienenverkehr', 'verkehrsweg', 'personenverkehr', 'schienennetz', 'verkehrsprojekt', 'fahrgast', 'schienenweg', 'verkehrsbereich', 'fernverkehr', 'bundesbahngesetz', 'verkehrsinfrastruktur', 'ag', 'werkfernverkehr', 'guterfernverkehr', 'tarif', 'verkehrsunternehm'] },
    { key: "topic_44", label: "Transport: Schiffahrt", searchList: ['schiff', 'haf', 'kust', 'see', 'bord', 'flagg', 'reed', 'marin', 'pirateri', 'seeschiffahrt', 'mittelme', 'golf', 'inseln', 'seeleut', 'schiffahrt', 'pirat', 'meer', 'kustenland', 'seehaf', 'zeichnung', 'kapitan', 'mittelmeerraum', 'reederei', 'koordinator', 'schlepp', 'schifffahrt', 'fregatt', 'besatz', 'seenotrett', 'seeweg'] },
    { key: "topic_45", label: "Recht & Kriminalität: Polizei & Grenzschutz", searchList: ['bundesgrenzschutz', 'grenzschutz', 'griech', 'bereitschaftspolizei', 'bmwi', 'ministerprasidentin', 'wismut', 'landerpolizei', 'sicherheitskonzept', 'polizeivollzugsbeamt', 'kad', 'formation', 'bundesparlament', 'bundesgrenzschutzgesetz', 'pensionsfond', 'landespolizei', 'grenzpolizei', 'gesellschaftsvertrag', 'regionalplan', 'grenzschutzbeamt', 'wertefundament', 'kosteneffizienz', 'polizeitrupp', 'sanierungsarbeit', 'frauenerwerbsquot', 'zehnpunkteprogramm', 'wasserschutzpolizei', 'passkontrolldien', 'politikgestalt', 'hundertschaft'] },
    { key: "topic_46", label: "Recht & Kriminalität: Drogenpolitik ", searchList: ['drog', 'alkohol', 'drogenpolit', 'therapi', 'drogenabhang', 'heroin', 'betaubungsmittelgesetz', 'kriminalitat', 'drogenhandel', 'rauschgift', 'aufklarungskampagn', 'abstinenz', 'verelend', 'drogenkonsum', 'drogenmissbrauch', 'verfassungsbestimm', 'wohnungseinbruch', 'rausch', 'rauschgiftkriminalitat', 'therapieplatz', 'drogenkriminalitat', 'behandeln', 'entkriminalisier', 'verfassungsdebatt', 'haschisch', 'drogensucht', 'drogentot', 'evaluierungsbericht', 'methadon', 'beschaffungskriminalitat'] },
    { key: "topic_47", label: "Recht & Kriminalität: Familienangelegenheiten ", searchList: ['mutt', 'vat', 'ehe', 'madch', 'familienpolit', 'ehegatt', 'erziehungsgeld', 'elternteil', 'hausfrau', 'scheidung', 'ehepartn', 'frauenhaus', 'lebensgemeinschaft', 'erwerbsarbeit', 'kindererzieh', 'erziehungsurlaub', 'ehen', 'erwerbsleb', 'versorgungsausgleich', 'flugplatz', 'sorgerecht', 'familienrecht', 'familienbericht', 'einwill', 'eheleut', 'unterhaltsrecht', 'teilzeitarbeitsplatz', 'misshandl', 'erzieh', 'lebensform'] },
    { key: "topic_48", label: "Recht & Kriminalität: Zivil und Strafrecht", searchList: ['straftat', 'straf', 'strafrecht', 'kriminalitat', 'staatsanwaltschaft', 'strafgesetzbuch', 'rechtspolit', 'stgb', 'freiheitsstraf', 'ehrenamt', 'strafverfolg', 'strafverfahr', 'straftatbestand', 'strafprozessordn', 'rechtsschutz', 'verjahr', 'ehefrau', 'vergewalt', 'beschuld', 'sicherungsverwahr', 'ermittlungsverfahr', 'menschenhandel', 'delikt', 'strafbar', 'sonderausschuss', 'verjahrungsfrist', 'angeklagt', 'ehemann', 'geldstraf', 'vernehm'] },
    { key: "topic_49", label: "Recht & Kriminalität: Sexualstrafrecht ", searchList: ['ehefrau', 'vergewalt', 'ehemann', 'notig', 'splitting', 'veranlag', 'sexualitat', 'verfuhr', 'sexualstrafrecht', 'feinheit', 'unehr', 'gegenwehr', 'atomabkomm', 'weiterarbeit', 'wahrheitsfind', 'kurzbeitrag', 'zusammenveranlag', 'einkommensbezieh', 'widerspruchsrecht', 'weltregion', 'strahlkraft', 'vortret', 'entschadigungsfrag', 'ganzheit', 'aushilf', 'marktverhaltnis', 'geschlechtsverkehr', 'extremsituation', 'hochschulbund', 'aufklarungspflicht'] },
    { key: "topic_50", label: "Recht & Kriminalität: Innerdeutscher Terrorismus", searchList: ['terrorismus', 'anschlag', 'terrorist', 'terror', 'sicherheitsbehord', 'verdacht', 'terroranschlag', 'attentat', 'terrorismusbekampf', 'sicherheitsarchitektur', 'nahrbod', 'besonn', 'vorverurteil', 'bedrohungslag', 'entfuhr', 'sicherheitslag', 'terrorgrupp', 'terrororganisation', 'terrorbekampf', 'extremist', 'ermord', 'terrorakt', 'generalbundesanwalt', 'gefahrdungslag', 'mordanschlag', 'sicherheitspaket', 'gefahrenlag', 'irakkrieg', 'fernsprechbuch', 'kriminalitat'] },
    { key: "topic_51", label: "Recht & Kriminalität: Wirtschaftskriminalität", searchList: ['steuerhinterzieh', 'therapi', 'bafin', 'abgabenordn', 'informationsaustausch', 'steueroas', 'fiskus', 'selbstanzeig', 'steuergerecht', 'doppelbesteuerungsabkomm', 'finanzbehord', 'quellensteu', 'diagnos', 'steuerpflicht', 'steuerbetrug', 'steuergestalt', 'lektion', 'bankgeheimnis', 'steuergeheimnis', 'steuerehr', 'jugendfrag', 'sicherungsmassnahm', 'steuerflucht', 'finanzaufsicht', 'steuervermeid', 'kapitalertragsteu', 'steuerrecht', 'prospekt', 'steuerabkomm', 'schweiz'] },
    { key: "topic_52", label: "Sozialpolitik: Renten", searchList: ['rent', 'rentenversicher', 'rentn', 'beitragszahl', 'rentenreform', 'altersvorsorg', 'riest', 'rentnerinn', 'massenarbeitslos', 'bundeszuschuss', 'beitragssatz', 'rucklag', 'rentenversicherungstrag', 'altersarmut', 'witw', 'alterssicher', 'rentenanpass', 'rentenpolit', 'versich', 'rentenniveau', 'rentenerhoh', 'rentenrecht', 'rentenanspruch', 'versicherungstrag', 'grundsicher', 'rentenkass', 'angestelltenversicher', 'abschlag', 'sozialversicherungstrag', 'rentenanpassungsgesetz'] },
    { key: "topic_53", label: "Sozialpolitik: Geringverdiener", searchList: ['armut', 'sozialhilf', 'arbeitslosenhilf', 'regelsatz', 'sozialhilfeempfang', 'existenzminimum', 'reichtum', 'bundessozialhilfegesetz', 'kinderarmut', 'weltbank', 'erwerbslos', 'sozialamt', 'armutsbekampf', 'wohlfahrtsverband', 'reichtumsbericht', 'lebenslag', 'schuldenerlass', 'umweltzerstor', 'verschiebebahnhof', 'alg', 'sozialhilfetrag', 'gerechtigkeitsluck', 'familienministerium', 'zumutbar', 'hartz', 'wahrungsfond', 'bshg', 'iter', 'uberschuld', 'regierungskommission'] },
    { key: "topic_54", label: "Sozialpolitik: Kindergeld & Jugendhilfe", searchList: ['kindergeld', 'alleinerzieh', 'einkommensgrenz', 'jugendhilf', 'kinderfreibetrag', 'familienlastenausgleich', 'freibetrag', 'familienpolit', 'jugendamt', 'jugendarbeit', 'jugendpolit', 'bundesjugendplan', 'abwert', 'jugendbericht', 'kindergelderhoh', 'ehegattensplitting', 'leistungsverbesser', 'kindergeldgesetz', 'jugendverband', 'kinderzuschlag', 'familienforder', 'existenzminimum', 'sozialarbeit', 'absetzbar', 'jugendorganisation', 'elternhaus', 'kindheit', 'kinderschutz', 'steuerfreibetrag', 'jugendhilfegesetz'] },
    { key: "topic_55", label: "Sozialpolitik: Bürger:Innenversicherung", searchList: ['zusatzbeitrag', 'burgerversicher', 'gesundheitsfond', 'praxisgebuhr', 'klientelpolit', 'kopfpauschal', 'psychotherapeut', 'sozialausgleich', 'finanzierungsgrundlag', 'psychotherapi', 'geringverdi', 'arbeitgeberbeitrag', 'therapeut', 'belastungsgrenz', 'standortentscheid', 'gutverdien', 'einfri', 'zielgross', 'ubergangszeitraum', 'einkommensschwach', 'unterdeck', 'versicherungsleist', 'arztbesuch', 'sparbeitrag', 'paritat', 'zusatzversicher', 'dienstverpflicht', 'vorkass', 'sonderbeitrag', 'steuerzuschuss'] },
    { key: "topic_56", label: "Binnenhandel: Verbraucherschutz", searchList: ['verbraucherschutz', 'verbraucherinn', 'verbraucherpolit', 'drohn', 'handl', 'verbraucherzentral', 'verbraucherinformationsgesetz', 'verbraucherverband', 'lebensmittelsich', 'supermarkt', 'vertragsabschluss', 'geschaftsbeding', 'risikobewert', 'verbraucherinformation', 'abzock', 'tuv', 'rechtsverstoss', 'bundesinstitut', 'wurst', 'lebensdau', 'verbraucherrecht', 'handys', 'verbraucherinteress', 'kundinn', 'marktwacht', 'politikum', 'verbraucheraufklar', 'informationskampagn', 'rechtsdurchsetz', 'kampfdrohn'] },
    { key: "topic_57", label: "Binnenhandel: Mittelstand", searchList: ['mittelstand', 'existenzgrund', 'mittelstandl', 'manag', 'mittelstandspolit', 'eigenkapital', 'freiberufl', 'neugrund', 'unternehmerinn', 'unternehmensgrund', 'mittelstandsforder', 'grosskonzern', 'pleit', 'kleinunternehm', 'selbststand', 'unternehmertum', 'forderpolit', 'eigenkapitalhilfeprogramm', 'risikobereitschaft', 'managergehalt', 'wagniskapital', 'innovationsprogramm', 'eigenkapitalquot', 'eigenkapitalausstatt', 'ausgleichsbank', 'risikokapital', 'eigenkapitalbasis', 'unternehmensberat', 'technologieunternehm', 'erfolgsrezept'] },
    { key: "topic_58", label: "Verteidigungspolitik: Nachkriegsordnung", searchList: ['streitkraft', 'trupp', 'arme', 'kriegsgefang', 'division', 'stab', 'wehrmacht', 'landesverteid', 'streitfrag', 'embargo', 'geiseln', 'kriegsgefangenschaft', 'kampfkraft', 'panz', 'hauptquarti', 'verteidigungsanstreng', 'brigad', 'korps', 'schlagkraft', 'bewaffn', 'wehrstruktur', 'verantwortungsgefuhl', 'verteidigungsbereitschaft', 'handelsbezieh', 'verteidigungsbeitrag', 'verteidigungsfah', 'stationier', 'heer', 'wehrverfass', 'vermiss'] },
    { key: "topic_59", label: "Verteidigungspolitik: Rüstungskontrolle ", searchList: ['abrust', 'pakt', 'atomwaff', 'rustungskontroll', 'bomb', 'abschreck', 'nuklearwaff', 'massenvernichtungswaff', 'paritat', 'nichtverbreitungsvertrag', 'bewaffn', 'kernwaff', 'atombomb', 'nichtverbreit', 'sicherheitsinteress', 'abrustungspolit', 'gipfelkonferenz', 'vertrauensbild', 'atomwaffensperrvertrag', 'grossmacht', 'krafteverhaltnis', 'mbfr', 'atommacht', 'atomkrieg', 'salt', 'uberprufungskonferenz', 'verfugungsgewalt', 'vertragspartei', 'inspektion', 'wettrust'] },
    { key: "topic_60", label: "Verteidigungspolitik: Militärische Unterstützung und Waffenlieferung", searchList: ['mandat', 'soldat', 'export', 'mission', 'soldatinn', 'liefer', 'rustungsexport', 'ausfahr', 'is', 'saudi', 'rustungsgut', 'waff', 'bundeswehr', 'waffenliefer', 'panz', 'waffenexport', 'auslandseinsatz', 'jem', 'kriegswaff', 'aussenwirtschaftsgesetz', 'rustungsindustri', 'bundessicherheitsrat', 'bundeswehreinsatz', 'rustungsexportpolit', 'awacs', 'bundeswehrsoldat', 'exporteur', 'isaf', 'kriegswaffenkontrollgesetz', 'kleinwaff'] },
    { key: "topic_61", label: "Technologie: Digitalisierung", searchList: ['digitalisier', 'liegenschaft', 'transformation', 'it', 'breitbandausbau', 'frequenz', 'tierarzt', 'groko', 'versteiger', 'digitalpakt', 'intellektuell', 'merkblatt', 'vertragsentwurf', 'automatisier', 'sicherheitsluck', 'produktionsfaktor', 'megabit', 'verschlussel', 'sicherheitsgesetz', 'modernitat', 'veranderungsprozess', 'smartphon', 'weiterbeschaft', 'robot', 'breitbandversorg', 'pfing', 'aktivist', 'formali', 'arbeitspapi', 'breitscheidplatz'] },
    { key: "topic_62", label: "Technologie: Rundfunk", searchList: ['fernseh', 'rundfunk', 'anstalt', 'ratifizier', 'sendung', 'rundfunkanstalt', 'radio', 'bildschirm', 'send', 'fernsehprogramm', 'ratifikation', 'ausstrahl', 'fernsehanstalt', 'intendant', 'hausangestellt', 'ratifizierungsgesetz', 'aufsichtsgremi', 'horfunk', 'massenmedi', 'ratifizierungsverfahr', 'fernsehs', 'ratifikationsgesetz', 'rundfunkgebuhr', 'werbefernseh', 'ratifikationsurkund', 'sendezeit', 'programmgestalt', 'reformvertrag', 'fernsehzuschau', 'beschwerdeverfahr'] },
    { key: "topic_63", label: "Außenhandel: Globalisierung & Weltwirtschaft", searchList: ['globalisier', 'weltwirtschaft', 'export', 'welthandel', 'protektionismus', 'wechselkurs', 'weltwirtschaftsgipfel', 'expo', 'direktinvestition', 'club', 'exportwirtschaft', 'aussenwirtschaft', 'zahlungsbilanz', 'exportnation', 'wahrungsfond', 'wachstumskraft', 'gatt', 'lokomotiv', 'inszenier', 'schwellenland', 'exportuberschuss', 'handelspartn', 'exportchanc', 'binnenwirtschaft', 'wechselkur', 'zufluss', 'heiligendamm', 'halbzeitbilanz', 'wachstumsprozess', 'anpassungsfah'] },
    { key: "topic_64", label: "Außenhandel: Handelsabkommen", searchList: ['freihandelsabkomm', 'handelspolit', 'ttip', 'handelsabkomm', 'freihandel', 'schwerpunktsetz', 'wirtschaftsbezieh', 'wirtschaftssyst', 'abschott', 'zollunion', 'handelspartn', 'multilateralismus', 'atlant', 'gipfeltreff', 'wirtschaftssystem', 'regierungsstell', 'verhandlungsmandat', 'handelshemmnis', 'investitionsschutz', 'karib', 'handelsbezieh', 'warenaustausch', 'guerilla', 'wirtschaftspartnerschaftsabkomm', 'investitionshaushalt', 'kooperationspartn', 'akp', 'kostenvorteil', 'sonderfond', 'mercosur'] },
    { key: "topic_65", label: "Außenpolitik: Entwicklungspolitik", searchList: ['entwicklungsland', 'entwicklungspolit', 'entwicklungshilf', 'entwicklungszusammenarbeit', 'hung', 'partnerland', 'nichtregierungsorganisation', 'kinderarbeit', 'us', 'schwellenland', 'armutsbekampf', 'weltbevolker', 'weltbank', 'regierungsfuhr', 'weltwirtschaftsordn', 'geberland', 'kleinbau', 'bruttosozialprodukt', 'budgethilf', 'entwicklungsfond', 'koharenz', 'kapitalhilf', 'entwicklungsprozess', 'planet', 'entwicklungsminist', 'lomé', 'nahrungsmittelhilf', 'afrikan', 'grundbedurfnis', 'entwicklungsprojekt'] },
    { key: "topic_66", label: "Außenpolitik: Europa", searchList: ['wahrungsunion', 'europapolit', 'nationalstaat', 'vertief', 'brit', 'regierungskonferenz', 'einigungsprozess', 'subsidiaritatsprinzip', 'integrationsprozess', 'europaausschuss', 'kommissionsprasident', 'wirtschaftsunion', 'konvergenz', 'populist', 'mehrheitsentscheid', 'haushaltsdisziplin', 'strukturfond', 'dreieck', 'parallelitat', 'burgernah', 'renationalisier', 'nettozahl', 'europawahl', 'stabilitatskriteri', 'bundesverwaltungsamt', 'wahrungspolit', 'demokratiedefizit', 'ratifizier', 'subsidiaritatsprinzips', 'erfolgskontroll'] },
    { key: "topic_67", label: "Außenpolitik: Naher Osten", searchList: ['sicherheitsrat', 'soldat', 'zivilbevolker', 'burgerkrieg', 'friedensprozess', 'sudsudan', 'taliban', 'staatengemeinschaft', 'zivilist', 'trupp', 'sicherheitskraft', 'sicherheitslag', 'waffenstillstand', 'afghan', 'kongo', 'konfliktpartei', 'mission', 'friedensmission', 'polizist', 'arme', 'isaf', 'miliz', 'unmiss', 'aufstand', 'friedensabkomm', 'militar', 'hilfsorganisation', 'unamid', 'friedenstrupp', 'blauhelm'] },
    { key: "topic_68", label: "Außenpolitik: Ost-West Konflikt", searchList: ['entspann', 'entspannungspolit', 'ostpolit', 'auswart', 'schlussakt', 'friedenspolit', 'grundvertrag', 'isolier', 'viermachteabkomm', 'ostvertrag', 'formeln', 'weltmacht', 'korb', 'ostblockstaat', 'friedenssicher', 'einmarsch', 'weizsack', 'koexistenz', 'teilnehmerstaat', 'grossmacht', 'friedensordn', 'staatschef', 'volksrepubl', 'bundnispartn', 'weltpolit', 'entspannungsprozess', 'supermacht', 'sowjet', 'unterhandl', 'freiheitskampf'] },
    { key: "topic_69", label: "Öffentliche Verwaltung: Föderalismus", searchList: ['gemeind', 'gewerbesteu', 'foderalismus', 'finanzausgleich', 'ruhrgebiet', 'finanzreform', 'volkskamm', 'finanzausstatt', 'finanzkraft', 'gebietskorperschaft', 'ansiedl', 'landerfinanzausgleich', 'gemeindefinanzreform', 'minderjahr', 'finanzverfass', 'gemeindefinanz', 'ruhr', 'gemeindeverband', 'revi', 'finanzsituation', 'sozialunion', 'zentralismus', 'stadtetag', 'gewerbesteuerumlag', 'landerparlament', 'landeshaushalt', 'strukturkris', 'steuereinnahm', 'mitteldeutschland', 'kalend'] },
    { key: "topic_70", label: "Öffentliche Verwaltung: Post", searchList: ['ag', 'bundespost', 'fernmeldewes', 'verwaltungsrat', 'volksrepubl', 'gebuhrenerhoh', 'bundespostminist', 'oberfinanzdirektion', 'vorstandsvorsitz', 'regulierungsbehord', 'aussenhandelsfrag', 'postminist', 'grundversorg', 'postreform', 'borsengang', 'zustell', 'postgesetz', 'universaldien', 'postamt', 'postverwaltungsrat', 'monopolist', 'postverwaltungsgesetz', 'abliefer', 'postgewerkschaft', 'postdien', 'postdienstleist', 'schalt', 'absend', 'telekommunikationsmarkt', 'rationalisierungsmassnahm'] },
    { key: "topic_71", label: "Öffentliche Verwaltung: Soziale Leistungen für Angestellte im öffentlichen Dienst", searchList: ['beamt', 'zulag', 'ruhestand', 'beamtenrecht', 'pension', 'beamtinn', 'feiertag', 'personalpolit', 'besoldungsgrupp', 'dienstrecht', 'berufsbeamtentum', 'versorgungsbezug', 'beamtenschaft', 'laufbahn', 'weihnachtsgeld', 'haushaltsstrukturgesetz', 'fursorgepflicht', 'arbeitseinkomm', 'versorgungsempfang', 'beamtengesetz', 'bundesbeamtengesetz', 'beamtenverhaltnis', 'bundesbeamt', 'ernenn', 'pensionar', 'abgeltungsteu', 'dienstherr', 'besoldungsrecht', 'versetz', 'beamtenbesold'] },
    { key: "topic_72", label: "Öffentliche Verwaltung: Korruption & Lobbyismus", searchList: ['korruption', 'versohn', 'interessenvertret', 'affar', 'lobbyist', 'gramm', 'bestech', 'biokraftstoff', 'wirtschaftspruf', 'biomass', 'steuerberat', 'misswirtschaft', 'verfehl', 'zertifizier', 'lobbyismus', 'sumpf', 'geldgeb', 'amtstrag', 'korruptionsbekampf', 'abgeordnetenbestech', 'dienstwag', 'anzeigepflicht', 'umfrageergebnis', 'hinterzimm', 'abschlusspruf', 'hauptfrag', 'verbandsvertret', 'schmiergeld', 'aufbewahrungsfrist', 'bvvg'] }
  ];
export const genderFilterOptions: DataProps[] = [
  { key: "gender_0", label: "Männer" },
  { key: "gender_1", label: "Frauen" },
  { key: "gender_2", label: "Unbekannt" },
  // { key: "2", label: "unknown" },
];

export const partyFilterOptions: DataProps[] = [
  { key: "party_0", label: "CDU/CSU" },
  { key: "party_1", label: "SPD" },
  { key: "party_2", label: "FDP" },
  { key: "party_3", label: "Gruene" },
  { key: "party_4", label: "DIE LINKE" },
  { key: "party_5", label: "AfD" },
  // { key: "6", label: "other" },
];

// prettier-ignore
export const politicianFilterOptions: DataProps[] = [
  { key: "politician_11000009", label: "Konrad Adenauer (CDU/CSU)" },
  { key: "politician_11000093", label: "Sabine Bard (Grüne)" },
  { key: "politician_11000102", label: "Rainer Barzel (CDU/CSU)" },
  { key: "politician_11000130", label: "Max Becker (FDP)" },
  { key: "politician_11000234", label: "Annemarie Borgmann (Grüne)" },
  { key: "politician_11000246", label: "Willy Brandt (SPD)" },
  { key: "politician_11000263", label: "Heinrich Brentano (CDU/CSU)" },
  { key: "politician_11000305", label: "Edelgard Bulmahn (SPD)" },
  { key: "politician_11000321", label: "Karl Carstens (CDU/CSU)" },
  { key: "politician_11000347", label: "Herta Däubler-Gmelin (SPD)" },
  { key: "politician_11000364", label: "Thomas Dehler (FDP)" },
  { key: "politician_11000365", label: "Jörg Diether Dehm-Desoi (DIE LINKE.)" },
  { key: "politician_11000418", label: "Alfred Dregger (CDU/CSU)" },
  { key: "politician_11000486", label: "Ludwig Erhard (CDU/CSU)" },
  { key: "politician_11000488", label: "Fritz Erler (SPD)" },
  { key: "politician_11000552", label: "Joschka Fischer (Grüne)" },
  { key: "politician_11000691", label: "Michael Glos (CDU/CSU)" },
  { key: "politician_11000756", label: "Gregor Gysi (DIE LINKE.)" },
  { key: "politician_11000924", label: "Hannegret Hönes (Grüne)" },
  { key: "politician_11000952", label: "Birgit Homburger (FDP)" },
  { key: "politician_11000964", label: "Willi Hoss (Grüne)" },
  { key: "politician_11001023", label: "Ulla Jelpke (DIE LINKE.)" },
  { key: "politician_11001074", label: "Volker Kauder (CDU/CSU)" },
  { key: "politician_11001081", label: "Petra Karin Kelly (Grüne)" },
  { key: "politician_11001096", label: "Kurt Georg Kiesinger (CDU/CSU)" },
  { key: "politician_11001136", label: "Hans Ulrich Klose (SPD)" },
  { key: "politician_11001165", label: "Helmut Kohl (CDU/CSU)" },
  { key: "politician_11001225", label: "Heinrich Krone (CDU/CSU)" },
  { key: "politician_11001336", label: "Sabine Leutheusser-Schnarrenberger (FDP)" },
  { key: "politician_11001352", label: "Helmut Lippelt (Grüne)" },
  { key: "politician_11001478", label: "Angela Merkel (CDU/CSU)" },
  { key: "politician_11001512", label: "Wolfgang Mischnick (FDP)" },
  { key: "politician_11001570", label: "Franz Müntefering (SPD)" },
  { key: "politician_11001637", label: "Jutta Oesterle-Schwerin (Grüne)" },
  { key: "politician_11001646", label: "Erich Ollenhauer (SPD)" },
  { key: "politician_11001772", label: "Peter Ramsauer (CDU/CSU)" },
  { key: "politician_11001933", label: "Hermann Schäfer (FDP)" },
  { key: "politician_11001938", label: "Wolfgang Schäuble (CDU/CSU)" },
  { key: "politician_11002003", label: "Christian Schmidt (CDU/CSU)" },
  { key: "politician_11002007", label: "Helmut Schmidt (SPD)" },
  { key: "politician_11002016", label: "Renate Schmidt (SPD)" },
  { key: "politician_11002019", label: "Ulla Schmidt (SPD)" },
  { key: "politician_11002065", label: "Waltraud Schoppe (Grüne)" },
  { key: "politician_11002078", label: "Gerhard Schröder (SPD)" },
  { key: "politician_11002140", label: "Horst Seehofer (CDU/CSU)" },
  { key: "politician_11002190", label: "Hermann Otto Solms (FDP)" },
  { key: "politician_11002365", label: "Christa Vennegerts (Grüne)" },
  { key: "politician_11002379", label: "Hans Jochen Vogel (SPD)" },
  { key: "politician_11002391", label: "Antje Vollmer (Grüne)" },
  { key: "politician_11002393", label: "Ludger Volmer (Grüne)" },
  { key: "politician_11002444", label: "Herbert Wehner (SPD)" },
  { key: "politician_11002503", label: "Heidemarie Wieczorek-Zeul (SPD)" },
  { key: "politician_11002617", label: "Peter Altmaier (CDU/CSU)" },
  { key: "politician_11002624", label: "Marieluise Beck-Oberdorf (Grüne)" },
  { key: "politician_11002652", label: "Andrea Fischer (Grüne)" },
  { key: "politician_11002659", label: "Wolfgang Gerhardt (FDP)" },
  { key: "politician_11002666", label: "Hermann Gröhe (CDU/CSU)" },
  { key: "politician_11002672", label: "Barbara Hendricks (SPD)" },
  { key: "politician_11002715", label: "Oskar Lafontaine (DIE LINKE.)" },
  { key: "politician_11002720", label: "Steffi Lemke (Grüne)" },
  { key: "politician_11002735", label: "Friedrich Merz (CDU/CSU)" },
  { key: "politician_11002742", label: "Gerd Müller (CDU/CSU)" },
  { key: "politician_11002746", label: "Cem Özdemir (Grüne)" },
  { key: "politician_11002765", label: "Norbert Röttgen (CDU/CSU)" },
  { key: "politician_11002769", label: "Rudolf Scharping (SPD)" },
  { key: "politician_11002823", label: "Ute Vogt (SPD)" },
  { key: "politician_11002944", label: "Guido Westerwelle (FDP)" },
  { key: "politician_11003028", label: "Ilse Aigner (CDU/CSU)" },
  { key: "politician_11003034", label: "Dietmar Bartsch (DIE LINKE.)" },
  { key: "politician_11003050", label: "Lothar Binding (SPD)" },
  { key: "politician_11003051", label: "Kurt Bodewig (SPD)" },
  { key: "politician_11003059", label: "Rainer Brüderle (FDP)" },
  { key: "politician_11003065", label: "Roland Claus (DIE LINKE.)" },
  { key: "politician_11003068", label: "Ekin Deligöz (Grüne)" },
  { key: "politician_11003124", label: "Hans Peter Friedrich (CDU/CSU)" },
  { key: "politician_11003132", label: "Katrin Dagmar Göring-Eckardt (Grüne)" },
  { key: "politician_11003142", label: "Hubertus Heil (SPD)" },
  { key: "politician_11003167", label: "Christine Lambrecht (SPD)" },
  { key: "politician_11003168", label: "Christian Lange (SPD)" },
  { key: "politician_11003196", label: "Andrea Nahles (SPD)" },
  { key: "politician_11003198", label: "Dirk Niebel (FDP)" },
  { key: "politician_11003213", label: "Michael Roth (SPD)" },
  { key: "politician_11003218", label: "Carsten Schneider (SPD)" },
  { key: "politician_11003231", label: "Olaf Scholz (SPD)" },
  { key: "politician_11003246", label: "Jürgen Trittin (Grüne)" },
  { key: "politician_11003259", label: "Annette Widmann-Mauz (CDU/CSU)" },
  { key: "politician_11003440", label: "Kerstin Griese (SPD)" },
  { key: "politician_11003493", label: "Kerstin Andreae (Grüne)" },
  { key: "politician_11003495", label: "Daniel Bahr (FDP)" },
  { key: "politician_11003496", label: "Sören Bartol (SPD)" },
  { key: "politician_11003510", label: "Helge Braun (CDU/CSU)" },
  { key: "politician_11003516", label: "Alexander Dobrindt (CDU/CSU)" },
  { key: "politician_11003522", label: "Hans Eichel (SPD)" },
  { key: "politician_11003530", label: "Otto Fricke (FDP)" },
  { key: "politician_11003541", label: "Michael Grosse-Brömer (CDU/CSU)" },
  { key: "politician_11003543", label: "Karl Theodor Guttenberg (CDU/CSU)" },
  { key: "politician_11003566", label: "Julia Klöckner (CDU/CSU)" },
  { key: "politician_11003569", label: "Kristina Köhler (CDU/CSU)" },
  { key: "politician_11003576", label: "Renate Künast (Grüne)" },
  { key: "politician_11003586", label: "Dorothee Mantel (CDU/CSU)" },
  { key: "politician_11003588", label: "Hilde Mattheis (SPD)" },
  { key: "politician_11003597", label: "Stefan Müller (CDU/CSU)" },
  { key: "politician_11003599", label: "Rolf Mützenich (SPD)" },
  { key: "politician_11003612", label: "Florian Pronold (SPD)" },
  { key: "politician_11003613", label: "Daniela Raab (CDU/CSU)" },
  { key: "politician_11003616", label: "Walter Riester (SPD)" },
  { key: "politician_11003625", label: "Andreas Scheuer (CDU/CSU)" },
  { key: "politician_11003631", label: "Uwe Schummer (CDU/CSU)" },
  { key: "politician_11003638", label: "Jens Spahn (CDU/CSU)" },
  { key: "politician_11003655", label: "Marco Wanderwitz (CDU/CSU)" },
  { key: "politician_11003710", label: "Bärbel Kofler (SPD)" },
  { key: "politician_11003714", label: "Monika Lazar (Grüne)" },
  { key: "politician_11003715", label: "Lars Klingbeil (SPD)" },
  { key: "politician_11003732", label: "Niels Annen (SPD)" },
  { key: "politician_11003734", label: "Thomas Bareiß (CDU/CSU)" },
  { key: "politician_11003746", label: "Sevim Dağdelen (DIE LINKE.)" },
  { key: "politician_11003753", label: "Klaus Ernst (DIE LINKE.)" },
  { key: "politician_11003755", label: "Sigmar Gabriel (SPD)" },
  { key: "politician_11003756", label: "Kai Gehring (Grüne)" },
  { key: "politician_11003763", label: "Heike Hänsel (DIE LINKE.)" },
  { key: "politician_11003764", label: "Britta Haßelmann (Grüne)" },
  { key: "politician_11003772", label: "Anton Hofreiter (Grüne)" },
  { key: "politician_11003781", label: "Franz Josef Jung (CDU/CSU)" },
  { key: "politician_11003786", label: "Katja Kipping (DIE LINKE.)" },
  { key: "politician_11003790", label: "Jan Korte (DIE LINKE.)" },
  { key: "politician_11003792", label: "Sylvia Kotting-Uhl (Grüne)" },
  { key: "politician_11003797", label: "Karl Lauterbach (SPD)" },
  { key: "politician_11003820", label: "Thomas Oppermann (SPD)" },
  { key: "politician_11003830", label: "Sönke Rix (SPD)" },
  { key: "politician_11003834", label: "Frank Schäffler (FDP)" },
  { key: "politician_11003836", label: "Annette Schavan (CDU/CSU)" },
  { key: "politician_11003846", label: "Frank Schwabe (SPD)" },
  { key: "politician_11003848", label: "Petra Sitte (DIE LINKE.)" },
  { key: "politician_11003856", label: "Florian Toncar (FDP)" },
  { key: "politician_11003860", label: "Kai Wegner (CDU/CSU)" },
  { key: "politician_11003870", label: "Brigitte Zypries (SPD)" },
  { key: "politician_11003881", label: "Omid Nouripour (Grüne)" },
  { key: "politician_11003888", label: "Wolfgang Strengmann-Kuhn (Grüne)" },
  { key: "politician_11003889", label: "Manuel Sarrazin (Grüne)" },
  { key: "politician_11003890", label: "Christian Hirte (CDU/CSU)" },
  { key: "politician_11004006", label: "Bärbel Bas (SPD)" },
  { key: "politician_11004011", label: "Steffen Bilger (CDU/CSU)" },
  { key: "politician_11004012", label: "Matthias W. Birkwald (DIE LINKE.)" },
  { key: "politician_11004021", label: "Ralph Brinkhaus (CDU/CSU)" },
  { key: "politician_11004022", label: "Christine Buchholz (DIE LINKE.)" },
  { key: "politician_11004023", label: "Marco Buschmann (FDP)" },
  { key: "politician_11004029", label: "Bijan Djir-Sarai (FDP)" },
  { key: "politician_11004030", label: "Katja Dörner (Grüne)" },
  { key: "politician_11004041", label: "Nicole Gohlke (DIE LINKE.)" },
  { key: "politician_11004048", label: "Florian Hahn (CDU/CSU)" },
  { key: "politician_11004050", label: "Jürgen Hardt (CDU/CSU)" },
  { key: "politician_11004057", label: "Manuel Höferlin (FDP)" },
  { key: "politician_11004060", label: "Andrej Hunko (DIE LINKE.)" },
  { key: "politician_11004061", label: "Thomas Jarzombek (CDU/CSU)" },
  { key: "politician_11004065", label: "Stefan Kaufmann (CDU/CSU)" },
  { key: "politician_11004068", label: "Roderich Kiesewetter (CDU/CSU)" },
  { key: "politician_11004070", label: "Sven Christian Kindler (Grüne)" },
  { key: "politician_11004072", label: "Maria Klein-Schmeink (Grüne)" },
  { key: "politician_11004079", label: "Daniela Kolbe (SPD)" },
  { key: "politician_11004081", label: "Oliver Krischer (Grüne)" },
  { key: "politician_11004085", label: "Stephan Kühn (Grüne)" },
  { key: "politician_11004088", label: "Caren Lay (DIE LINKE.)" },
  { key: "politician_11004089", label: "Sabine Leidig (DIE LINKE.)" },
  { key: "politician_11004092", label: "Ursula Leyen (CDU/CSU)" },
  { key: "politician_11004093", label: "Stefan Liebich (DIE LINKE.)" },
  { key: "politician_11004097", label: "Christian Lindner (FDP)" },
  { key: "politician_11004100", label: "Jan Marco Luczak (CDU/CSU)" },
  { key: "politician_11004102", label: "Oliver Luksic (FDP)" },
  { key: "politician_11004106", label: "Agnes Malczak (Grüne)" },
  { key: "politician_11004111", label: "Cornelia Möhring (DIE LINKE.)" },
  { key: "politician_11004114", label: "Niema Movassat (DIE LINKE.)" },
  { key: "politician_11004116", label: "Nadine Müller (CDU/CSU)" },
  { key: "politician_11004117", label: "Beate Müller-Gemmeke (Grüne)" },
  { key: "politician_11004123", label: "Konstantin Notz (Grüne)" },
  { key: "politician_11004127", label: "Lisa Paus (Grüne)" },
  { key: "politician_11004138", label: "Tabea Rößner (Grüne)" },
  { key: "politician_11004139", label: "Erwin Rüddel (CDU/CSU)" },
  { key: "politician_11004143", label: "Tankred Schipanski (CDU/CSU)" },
  { key: "politician_11004146", label: "Patrick Schnieder (CDU/CSU)" },
  { key: "politician_11004165", label: "Peer Steinbrück (SPD)" },
  { key: "politician_11004167", label: "Frank Walter Steinmeier (SPD)" },
  { key: "politician_11004174", label: "Peter Tauber (CDU/CSU)" },
  { key: "politician_11004176", label: "Wolfgang Tiefensee (SPD)" },
  { key: "politician_11004179", label: "Johannes Vogel (FDP)" },
  { key: "politician_11004183", label: "Sahra Wagenknecht (DIE LINKE.)" },
  { key: "politician_11004215", label: "Harald Ebner (Grüne)" },
  { key: "politician_11004217", label: "Tobias Lindner (Grüne)" },
  { key: "politician_11004245", label: "Annalena Baerbock (Grüne)" },
  { key: "politician_11004247", label: "Katarina Barley (SPD)" },
  { key: "politician_11004255", label: "Franziska Brantner (Grüne)" },
  { key: "politician_11004257", label: "Lars Castellucci (SPD)" },
  { key: "politician_11004259", label: "Karamba Diaby (SPD)" },
  { key: "politician_11004263", label: "Katharina Dröge (Grüne)" },
  { key: "politician_11004267", label: "Saskia Esken (SPD)" },
  { key: "politician_11004272", label: "Fritz Felgentreu (SPD)" },
  { key: "politician_11004278", label: "Matthias Gastel (Grüne)" },
  { key: "politician_11004291", label: "Sebastian Hartmann (SPD)" },
  { key: "politician_11004292", label: "Matthias Hauer (CDU/CSU)" },
  { key: "politician_11004302", label: "Heribert Hirte (CDU/CSU)" },
  { key: "politician_11004303", label: "Thomas Hitschler (SPD)" },
  { key: "politician_11004312", label: "Dieter Janecek (Grüne)" },
  { key: "politician_11004323", label: "Anja Karliczek (CDU/CSU)" },
  { key: "politician_11004328", label: "Cansel Kiziltepe (SPD)" },
  { key: "politician_11004337", label: "Katja Leikert (CDU/CSU)" },
  { key: "politician_11004339", label: "Andreas Lenz (CDU/CSU)" },
  { key: "politician_11004353", label: "Irene Mihalic (Grüne)" },
  { key: "politician_11004361", label: "Alexander S. Neu (DIE LINKE.)" },
  { key: "politician_11004362", label: "Andreas Nick (CDU/CSU)" },
  { key: "politician_11004363", label: "Ulli Nissen (SPD)" },
  { key: "politician_11004385", label: "Martina Renner (DIE LINKE.)" },
  { key: "politician_11004395", label: "Ulle Schauws (Grüne)" },
  { key: "politician_11004398", label: "Jana Schimke (CDU/CSU)" },
  { key: "politician_11004405", label: "Kordula Schulz-Asche (Grüne)" },
  { key: "politician_11004426", label: "Carsten Träger (SPD)" },
  { key: "politician_11004429", label: "Julia Verlinden (Grüne)" },
  { key: "politician_11004443", label: "Kai Whittaker (CDU/CSU)" },
  { key: "politician_11004603", label: "Jens Zimmermann (SPD)" },
  { key: "politician_11004656", label: "Philipp Amthor (CDU/CSU)" },
  { key: "politician_11004659", label: "Lisa Badum (Grüne)" },
  { key: "politician_11004665", label: "Canan Bayram (Grüne)" },
  { key: "politician_11004672", label: "Lorenz Gösta Beutin (DIE LINKE.)" },
  { key: "politician_11004678", label: "Stephan Brandner (AfD)" },
  { key: "politician_11004692", label: "Petr Bystron (AfD)" },
  { key: "politician_11004695", label: "Tino Chrupalla (AfD)" },
  { key: "politician_11004698", label: "Gottfried Curio (AfD)" },
  { key: "politician_11004703", label: "Anke Domscheit-Berg (DIE LINKE.)" },
  { key: "politician_11004705", label: "Christian Dürr (FDP)" },
  { key: "politician_11004716", label: "Daniel Föst (FDP)" },
  { key: "politician_11004722", label: "Götz Frömming (AfD)" },
  { key: "politician_11004724", label: "Alexander Gauland (AfD)" },
  { key: "politician_11004731", label: "Kay Gottschalk (AfD)" },
  { key: "politician_11004749", label: "Martin Hess (AfD)" },
  { key: "politician_11004761", label: "Leif Erik Holm (AfD)" },
  { key: "politician_11004786", label: "Lukas Köhler (FDP)" },
  { key: "politician_11004796", label: "Konstantin Kuhle (FDP)" },
  { key: "politician_11004798", label: "Alexander Lambsdorff (FDP)" },
  { key: "politician_11004801", label: "Sven Lehmann (Grüne)" },
  { key: "politician_11004802", label: "Helge Lindh (SPD)" },
  { key: "politician_11004811", label: "Jens Maier (AfD)" },
  { key: "politician_11004817", label: "Fabio De Masi (DIE LINKE.)" },
  { key: "politician_11004823", label: "Amira Mohamed Ali (DIE LINKE.)" },
  { key: "politician_11004857", label: "Filiz Polat (Grüne)" },
  { key: "politician_11004858", label: "Stephan Protschka (AfD)" },
  { key: "politician_11004859", label: "Martin Reichardt (AfD)" },
  { key: "politician_11004869", label: "Thomas Sattelberger (FDP)" },
  { key: "politician_11004905", label: "Beatrix Storch (AfD)" },
  { key: "politician_11004906", label: "Marie Agnes Strack-Zimmermann (FDP)" },
  { key: "politician_11004908", label: "Benjamin Strasser (FDP)" },
  { key: "politician_11004910", label: "Katja Suding (FDP)" },
  { key: "politician_11004913", label: "Linda Teuteberg (FDP)" },
  { key: "politician_11004914", label: "Michael Theurer (FDP)" },
  { key: "politician_11004941", label: "Gyde Jensen (FDP)" },
  { key: "politician_11000500", label: "August Martin Euler (FDP, DA, FVP, DP)" },
  { key: "politician_11001242", label: "Knut Kühlmann-Stumm (FDP, CDU/CSU)" },
  { key: "politician_11001467", label: "Erich Mende (FDP, CDU/CSU)" },
  { key: "politician_11001970", label: "Otto Schily (Grüne, SPD)" },
  { key: "politician_11002248", label: "Ludwig Stiegler (SPD)" },
  { key: "politician_11002278", label: "Peter Struck (SPD)" },
  { key: "politician_11003206", label: "Petra Pau (DIE LINKE., Fraktionslos)" },
  { key: "politician_11003512", label: "Marco Bülow (SPD, Fraktionslos)" },
  { key: "politician_11003584", label: "Gesine Lötzsch (Fraktionslos, DIE LINKE.)" },
];

export const stateFilterOptions: DataProps[] = [
  { key: "state_0", label: "Ost" },
  { key: "state_1", label: "West" },
  // { key: "state_2", label: "Alle" },
];
export const ageFilterOptions: DataProps[] = [
  { key: "age_0", label: "Jünger als 50" },
  { key: "age_1", label: "50 oder Älter" },
  // { key: "age_2", label: "Alle" },
];
export const jobFilterOptions: DataProps[] = [
  { key: "job_0", label: "Recht" },
  { key: "job_1", label: "Wirtschaft" },
  { key: "job_2", label: "Naturwissenschaft" },
  { key: "job_3", label: "Gesellschaftswissenschaft" },
  { key: "job_4", label: "Agrar" },
  { key: "job_5", label: "Journalismus" },
  { key: "job_6", label: "Handwerk" },
  { key: "job_7", label: "Andere" },
];
