name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://open-discourse-ui-git-develop.ofranke.vercel.app/
            https://open-discourse-ui-git-develop.ofranke.vercel.app/volltextsuche
            https://open-discourse-ui-git-develop.ofranke.vercel.app/analysen
            https://open-discourse-ui-git-develop.ofranke.vercel.app/ueber-uns
          # budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
